(() => {
  "use strict";
  const cfg = window.ADER_CONFIG || {};
  const API = String(cfg.API_BASE || "").replace(/\/$/, "");
  const state = { user:null, guilds:[], guild:null, overview:null, resources:null, commands:[], shortcuts:[], tickets:null, teams:[], page:"overview", lang:cfg.DEFAULT_LANGUAGE||"ar", theme:cfg.DEFAULT_THEME||"discord" };
  const $ = (s) => document.querySelector(s);
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  const n = (v) => Number(v || 0).toLocaleString("en-US");
  const api = async (path, options = {}) => {
    const res = await fetch(API + path, { credentials:"include", ...options, headers:{"Content-Type":"application/json", ...(options.headers||{})} });
    if (res.status === 401) { showAuth(); throw new Error("AUTH"); }
    const text = await res.text();
    let data = {}; try { data = text ? JSON.parse(text) : {}; } catch { data = { detail:text }; }
    if (!res.ok) throw new Error(data.detail || data.message || `HTTP ${res.status}`);
    return data;
  };
  const toast = (message, type="success") => { const el=document.createElement("div"); el.className=`toast ${type}`; el.textContent=message; $("#toast-root").appendChild(el); setTimeout(()=>el.remove(),3200); };
  const showAuth = () => { $("#loading").classList.add("hidden"); $("#app").classList.add("hidden"); $("#login-screen").classList.remove("hidden"); };
  const hideAuth = () => { $("#login-screen").classList.add("hidden"); $("#app").classList.remove("hidden"); $("#loading").classList.add("hidden"); };
  const avatarUrl = (id, hash, size=128) => id && hash ? `https://cdn.discordapp.com/avatars/${id}/${hash}.png?size=${size}` : "";
  const icon = (g, size=64) => { const url = avatarUrl(g?.id, g?.icon, size); return url ? `<img src="${esc(url)}" alt="">` : esc((g?.name||"A").slice(0,1).toUpperCase()); };

  async function boot(){
    try {
      const me = await api("/api/me");
      if (!me.logged_in) return showAuth();
      state.user = me.user;
      const gs = await api("/api/guilds"); state.guilds = gs.guilds || [];
      if (!state.guilds.length) { hideAuth(); renderNoGuilds(); return; }
      state.guild = state.guilds[0];
      renderUser(); renderGuildSelect(); hideAuth(); await selectGuild(state.guild.id, false); navigate("overview");
    } catch (e) { if (e.message !== "AUTH") { showAuth(); toast("تعذر الاتصال بالـ API. تأكد من API_BASE و CORS.","error"); } }
  }
  function renderUser(){ const u=state.user||{}; $("#user-name").textContent=u.global_name||u.username||"Discord User"; const a=avatarUrl(u.id,u.avatar); $("#user-avatar").innerHTML=a?`<img src="${esc(a)}" alt="" style="width:100%;height:100%;border-radius:50%;object-fit:cover">`:(u.username||"U").slice(0,1).toUpperCase(); }
  function renderGuildSelect(){
    const select=$("#server-select"); select.innerHTML=state.guilds.map(g=>`<option value="${g.id}">${esc(g.name)}</option>`).join(""); select.value=String(state.guild?.id||""); select.onchange=()=>selectGuild(Number(select.value),true); updateGuildHeader(); $("#server-strip").classList.remove("hidden");
  }
  function updateGuildHeader(){ const g=state.guild; $("#server-name").textContent=g?.name||"اختار سيرفر"; $("#workspace-name").textContent=g?.name||"Ader"; $("#server-icon").innerHTML=icon(g); $("#workspace-avatar").innerHTML=icon(g); }
  async function selectGuild(id, announce=true){
    state.guild=state.guilds.find(g=>Number(g.id)===Number(id))||state.guilds[0]; updateGuildHeader(); $("#server-select").value=String(state.guild.id);
    try { const [o,r]=await Promise.all([api(`/api/guilds/${state.guild.id}/overview`),api(`/api/guilds/${state.guild.id}/resources`)]); state.overview=o; state.resources=r; if(announce) { toast(`تم اختيار ${state.guild.name}`); navigate(state.page); } } catch(e){ toast(e.message,"error"); }
  }
  function renderNoGuilds(){ hideAuth(); $("#server-strip").classList.add("hidden"); $("#page-root").innerHTML=`<div class="empty"><h2>ما كاين حتى سيرفر متاح</h2><p>خاصك تكون Administrator أو عندك Manage Server، والبوت يكون داخل السيرفر.</p></div>`; }
  const titles={overview:"Overview",servers:"السيرفرات",commands:"الأوامر",shortcuts:"Shortcuts",tickets:"Tickets",teams:"Teams",resources:"القنوات والرتب",settings:"Settings"};
  async function navigate(page){ state.page=page; document.querySelectorAll(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page)); $("#page-title").textContent=titles[page]||page; $("#sidebar").classList.remove("open"); const root=$("#page-root"); root.innerHTML=`<div class="empty">جاري تحميل ${esc(titles[page]||"")}...</div>`; try { if(page==="overview") renderOverview(); else if(page==="servers") renderServers(); else if(page==="commands") await loadCommands(); else if(page==="shortcuts") await loadShortcuts(); else if(page==="tickets") await loadTickets(); else if(page==="teams") await loadTeams(); else if(page==="resources") renderResources(); else renderSettings(); } catch(e){ root.innerHTML=`<div class="empty"><h3>تعذر تحميل الصفحة</h3><p>${esc(e.message)}</p></div>`; } }
  function head(title,desc,action=""){return `<div class="page-head"><div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div>${action?`<div class="page-actions">${action}</div>`:""}</div>`}
  function renderOverview(){
    const o=state.overview||{}; const g=state.guild;
    $("#page-root").innerHTML=head("مرحباً بك في Ader","إدارة سيرفرك، الإعدادات، والأدوات من لوحة واحدة.")+`<div class="stat-grid">
      ${stat("الأعضاء",n(o.members),"♙","Server members")}${stat("القنوات",n(o.channels),"#","Text & voice channels")}${stat("الرتب",n(o.roles),"◆","Server roles")}${stat("التذاكر المفتوحة",n(o.open_tickets),"▣","Open support tickets")}
    </div><div class="section-grid"><div class="card"><div class="card-head"><h3>حالة السيرفر</h3><span class="badge">Online</span></div><div class="card-body"><div class="health">${health("Ader latency",`${o.bot_latency_ms||0} ms`)}${health("Slash commands",n(o.commands))}${health("Permissions","Managed")}${health("Database","Connected")}</div></div></div><div class="card"><div class="card-head"><h3>الوصول السريع</h3></div><div class="card-body"><div class="toolbar"><button class="btn btn-primary" onclick="window.Ader.navigate('tickets')">إنشاء Ticket Panel</button><button class="btn" onclick="window.Ader.navigate('commands')">إدارة الأوامر</button><button class="btn" onclick="window.Ader.navigate('shortcuts')">Shortcuts</button></div><p class="muted">${esc(g?.name||"")} · آخر تحديث مباشر من Ader API.</p></div></div></div>`;
  }
  function stat(label,value,ico,foot){return `<div class="stat-card"><div class="stat-top"><span>${esc(label)}</span><span class="stat-icon">${ico}</span></div><div class="stat-value">${value}</div><div class="stat-foot">${esc(foot)}</div></div>`}
  function health(a,b){return `<div class="health-item"><small>${esc(a)}</small><b class="online">${esc(b)}</b></div>`}
  function renderServers(){
    $("#page-root").innerHTML=head("السيرفرات","السيرفرات اللي عندك صلاحية إدارتها.")+`<div class="server-grid">${state.guilds.map(g=>`<article class="server-card" onclick="window.Ader.pick(${g.id})"><div class="server-card-top"><div class="server-icon">${icon(g)}</div><div><b>${esc(g.name)}</b><div class="muted" style="font-size:10px;margin-top:4px">${g.administrator?"Administrator":"Manage Server"}</div></div></div><p>ID: ${esc(g.id)}</p></article>`).join("")}</div>`;
  }
  async function loadCommands(){
    const d=await api(`/api/guilds/${state.guild.id}/commands`); state.commands=d.commands||[]; let filtered=state.commands; const render=(list)=>{ $("#cmd-body").innerHTML=list.length?list.map((c,i)=>`<tr><td><div class="command-name">/${esc(c.name)}</div></td><td><div class="command-desc">${esc(c.description||"بدون وصف")}</div></td><td><span class="badge ${c.enabled?"":"off"}">${c.enabled?"مفعل":"معطل"}</span></td><td><button class="toggle ${c.enabled?"on":""}" onclick="window.Ader.toggleCommand(${i})"><i></i></button></td></tr>`).join(""):`<tr><td colspan="4"><div class="empty">ما لقيت حتى أمر.</div></td></tr>`; };
    $("#page-root").innerHTML=head("الأوامر","فعّل أو عطّل أوامر Ader لكل سيرفر.")+`<div class="toolbar"><input id="cmd-search" class="search" placeholder="بحث في الأوامر..."><button class="btn" onclick="window.Ader.refresh()">↻ تحديث</button></div><div class="card"><table class="table"><thead><tr><th>الأمر</th><th>الوصف</th><th>الحالة</th><th>تعديل</th></tr></thead><tbody id="cmd-body"></tbody></table></div>`; render(filtered); $("#cmd-search").oninput=e=>{const q=e.target.value.toLowerCase();render(state.commands.filter(x=>(x.name+" "+x.description).toLowerCase().includes(q)));};
  }
  async function toggleCommand(index){ const c=state.commands[index]; if(!c)return; const old=c.enabled; c.enabled=!old; try{await api(`/api/guilds/${state.guild.id}/commands/${encodeURIComponent(c.name)}`,{method:"PUT",body:JSON.stringify({enabled:c.enabled,allowed_roles:c.allowed_roles,denied_roles:c.denied_roles,allowed_channels:c.allowed_channels,denied_channels:c.denied_channels})}); toast(`${c.name}: ${c.enabled?"تم التفعيل":"تم التعطيل"}`); await loadCommands();}catch(e){c.enabled=old;toast(e.message,"error");} }
  async function loadShortcuts(){
    const d=await api(`/api/guilds/${state.guild.id}/shortcuts`); state.shortcuts=d.shortcuts||[]; const body=state.shortcuts.length?state.shortcuts.map((s,i)=>`<tr><td><b>${esc(s.label)}</b><div class="muted">${esc(s.name)}</div></td><td><input class="search" style="max-width:180px" value="${esc(s.alias||"")}" id="alias-${i}"></td><td><button class="toggle ${s.enabled?"on":""}" onclick="window.Ader.toggleShortcut(${i})"><i></i></button></td><td><button class="btn" onclick="window.Ader.saveShortcut(${i})">حفظ</button></td></tr>`).join(""): `<tr><td colspan="4"><div class="empty">ما كايناش Shortcuts حالياً.</div></td></tr>`;
    $("#page-root").innerHTML=head("Shortcuts","تحكم في الاختصارات والـ aliases ديال Ader.")+`<div class="card"><table class="table"><thead><tr><th>الاختصار</th><th>Alias</th><th>الحالة</th><th></th></tr></thead><tbody>${body}</tbody></table></div>`;
  }
  async function saveShortcut(i){const s=state.shortcuts[i], alias=$("#alias-"+i).value.trim();try{await api(`/api/guilds/${state.guild.id}/shortcuts/${encodeURIComponent(s.name)}`,{method:"PUT",body:JSON.stringify({alias,enabled:s.enabled,allowed_roles:s.allowed_roles,denied_roles:s.denied_roles,allowed_channels:s.allowed_channels,denied_channels:s.denied_channels})});toast("تم حفظ الاختصار");await loadShortcuts();}catch(e){toast(e.message,"error");}}
  async function toggleShortcut(i){state.shortcuts[i].enabled=!state.shortcuts[i].enabled;await saveShortcut(i);}
  async function loadTickets(){
    let data; try{data=await api(`/api/guilds/${state.guild.id}/tickets`);}catch(e){ if(String(e.message).includes("404")){data={panels:[],tickets:[]};} else throw e; } state.tickets=data;
    $("#page-root").innerHTML=head("Tickets","صمم Ticket Panels بطريقة احترافية وانشرها مباشرة في Discord.",`<button class="btn btn-primary" onclick="window.Ader.openTicketModal()">+ لوحة جديدة</button>`)+`<div class="section-grid"><div class="card"><div class="card-head"><h3>Ticket Panels</h3><span class="badge">${n(data.panels?.length)}</span></div><div class="card-body">${data.panels?.length?data.panels.map(p=>`<div class="resource"><b>${esc(p.title||"Ticket Panel")}</b><span>#${esc(p.channel_id||"")}</span></div>`).join(""):"<div class='empty'>مازال ما أنشأتي حتى Panel.</div>"}</div></div><div class="card"><div class="card-head"><h3>آخر التذاكر</h3></div><div class="card-body">${data.tickets?.length?data.tickets.slice(0,8).map(t=>`<div class="resource"><b>#${esc(t.id)}</b><span>${esc(t.status||"open")}</span></div>`).join(""):"<div class='empty'>ما كايناش تذاكر مسجلة.</div>"}</div></div></div>`;
  }
  async function loadTeams(){const d=await api(`/api/guilds/${state.guild.id}/teams`).catch(()=>({teams:[]}));state.teams=d.teams||[];$("#page-root").innerHTML=head("Teams","الفرق الموثقة وإحصائيات اللاعبين.")+`<div class="card"><div class="card-body">${state.teams.length?`<table class="table"><thead><tr><th>الفريق</th><th>النوع</th><th>اللاعبون</th></tr></thead><tbody>${state.teams.map(t=>`<tr><td><b>${esc(t.name||t.team_name||"Team")}</b></td><td>${esc(t.team_type||"—")}</td><td>${n(t.players)}</td></tr>`).join("")}</tbody></table>`:`<div class="empty">ما كايناش Teams موثقة حالياً.</div>`}</div></div>`;}
  function renderResources(){const r=state.resources||{roles:[],channels:[]};$("#page-root").innerHTML=head("القنوات والرتب","موارد السيرفر المتاحة للوحة Ader.")+`<div class="resource-grid"><div class="card"><div class="card-head"><h3>الرتب</h3><span class="badge">${n(r.roles.length)}</span></div><div class="card-body"><div class="resource-list">${r.roles.map(x=>`<div class="resource"><b>${esc(x.name)}</b><span>Position ${esc(x.position)}</span></div>`).join("")||"<div class='empty'>لا توجد رتب.</div>"}</div></div></div><div class="card"><div class="card-head"><h3>القنوات</h3><span class="badge">${n(r.channels.length)}</span></div><div class="card-body"><div class="resource-list">${r.channels.map(x=>`<div class="resource"><b>#${esc(x.name)}</b><span>${esc(x.type)}</span></div>`).join("")||"<div class='empty'>لا توجد قنوات.</div>"}</div></div></div></div>`;}
  function renderSettings(){ $("#page-root").innerHTML=head("Settings","إعدادات الواجهة والاتصال بالـ API.")+`<div class="section-grid"><div class="card"><div class="card-head"><h3>Appearance</h3></div><div class="card-body"><div class="toolbar"><button class="btn" onclick="window.Ader.theme('discord')">Discord Dark</button><button class="btn" onclick="window.Ader.theme('light')">Light</button></div><p class="muted">التغيير محفوظ محلياً في هذا المتصفح.</p></div></div><div class="card"><div class="card-head"><h3>Backend</h3></div><div class="card-body"><div class="resource"><b>API endpoint</b><span>${esc(API||"same-origin")}</span></div><div class="resource" style="margin-top:8px"><b>Server</b><span>${esc(state.guild?.name||"—")}</span></div></div></div></div>`; }
  function openTicketModal(){
    const r=state.resources||{channels:[],roles:[]}; const cats=r.channels.filter(x=>String(x.type).toLowerCase().includes("category")); const text=r.channels.filter(x=>String(x.type).toLowerCase().includes("text"));
    $("#modal-root").innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)window.Ader.closeModal()"><div class="modal"><div class="modal-head"><h3>إنشاء Ticket Panel</h3><button class="icon-btn" onclick="window.Ader.closeModal()">×</button></div><div class="modal-body"><div class="form-grid"><div class="field"><label>عنوان اللوحة</label><input id="ticket-title" value="🎫 الدعم الفني"></div><div class="field"><label>قناة نشر اللوحة</label><select id="ticket-channel">${text.map(x=>`<option value="${x.id}">#${esc(x.name)}</option>`).join("")}</select></div><div class="field"><label>Category</label><select id="ticket-category">${cats.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}</select></div><div class="field"><label>Support Role</label><select id="ticket-role"><option value="">بدون تحديد</option>${r.roles.map(x=>`<option value="${x.id}">@${esc(x.name)}</option>`).join("")}</select></div><div class="field full"><label>الوصف</label><textarea id="ticket-desc">اختار القسم المناسب لفتح تذكرة.</textarea></div><div class="field full"><label>صورة اللوحة (اختياري)</label><input id="ticket-image" placeholder="https://..."></div></div><div class="ticket-preview" style="margin-top:16px"><h3 id="preview-title">🎫 الدعم الفني</h3><p id="preview-desc">اختار القسم المناسب لفتح تذكرة.</p><div class="ticket-options"><span class="ticket-option">🎫 فتح تذكرة</span><span class="ticket-option">💬 Support</span></div></div><div class="form-actions"><button class="btn" onclick="window.Ader.closeModal()">إلغاء</button><button class="btn btn-primary" onclick="window.Ader.createTicketPanel()">نشر اللوحة</button></div></div></div></div>`;
    $("#ticket-title").oninput=e=>$("#preview-title").textContent=e.target.value||"🎫 الدعم الفني"; $("#ticket-desc").oninput=e=>$("#preview-desc").textContent=e.target.value||"";
  }
  async function createTicketPanel(){const payload={title:$("#ticket-title").value,description:$("#ticket-desc").value,image_url:$("#ticket-image").value||null,channel_id:Number($("#ticket-channel").value),category_id:Number($("#ticket-category").value),support_role_id:$("#ticket-role").value?Number($("#ticket-role").value):null,mode:"buttons",options:[{name:"فتح تذكرة",emoji:"🎫",ticket_name:"ticket-{user}",description:"فتح تذكرة"}]};try{await api(`/api/guilds/${state.guild.id}/tickets/panels`,{method:"POST",body:JSON.stringify(payload)});closeModal();toast("تم نشر Ticket Panel في Discord");await loadTickets();}catch(e){toast(e.message,"error");}}
  function closeModal(){$("#modal-root").innerHTML="";}
  function theme(t){state.theme=t;document.body.classList.toggle("light",t==="light");localStorage.setItem("ader-theme",t);}
  function language(){state.lang=state.lang==="ar"?"fr":"ar";document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==="ar"?"rtl":"ltr";$("#lang-btn").textContent=state.lang.toUpperCase();toast(state.lang==="ar"?"العربية":"Français");}
  function renderTheme(){const t=localStorage.getItem("ader-theme")||state.theme;theme(t);$("#lang-btn").textContent=state.lang.toUpperCase();}
  $("#login-btn").onclick=()=>{window.location.href=API+"/login"}; $("#logout-btn").onclick=()=>{window.location.href=API+"/logout"}; $("#refresh-btn").onclick=()=>window.Ader.refresh(); $("#theme-btn").onclick=()=>theme(document.body.classList.contains("light")?"discord":"light"); $("#lang-btn").onclick=language; $("#mobile-menu").onclick=()=>$("#sidebar").classList.add("open"); $("#mobile-close").onclick=()=>$("#sidebar").classList.remove("open"); document.querySelectorAll(".nav-item").forEach(b=>b.onclick=()=>navigate(b.dataset.page));
  window.Ader={navigate,pick:async(id)=>{await selectGuild(id,true);},toggleCommand,saveShortcut,toggleShortcut,openTicketModal,createTicketPanel,closeModal,theme,refresh:()=>navigate(state.page)};
  renderTheme(); boot();
})();
