(()=>{"use strict";
const API=String((window.ADER_CONFIG||{}).API_BASE||"").replace(/\/$/,"");
const s={user:null,guilds:[],guild:null,overview:{},resources:{roles:[],channels:[]},page:"overview"};
const $=x=>document.querySelector(x),esc=x=>String(x??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function api(p,o={}){const r=await fetch(API+p,{credentials:"include",cache:"no-store",headers:{"Content-Type":"application/json",...(o.headers||{})},...o});let t=await r.text(),d={};try{d=t?JSON.parse(t):{}}catch{d={detail:t}}if(r.status===401)throw Error("AUTH");if(!r.ok)throw Error(d.detail||d.message||"HTTP "+r.status);return d}
function icon(g){return g&&g.icon?'<img src="https://cdn.discordapp.com/icons/'+g.id+'/'+g.icon+'.png?size=128" alt="">':esc((g?.name||"A")[0])}
function showLogin(){ $("#loading").classList.add("hidden");$("#app").classList.add("hidden");$("#login").classList.remove("hidden")}
function showApp(){ $("#loading").classList.add("hidden");$("#login").classList.add("hidden");$("#app").classList.remove("hidden")}
function warn(m){$("#apiWarning").textContent=m;$("#apiWarning").classList.remove("hidden")}
function clearWarn(){$("#apiWarning").classList.add("hidden")}
function head(t,d){return '<div class="page-head"><div><h1>'+t+'</h1><p>'+d+'</p></div></div>'}
function card(t,b){return '<section class="card"><div class="card-head"><b>'+t+'</b></div><div class="card-body">'+b+'</div></section>'}
function stat(a,b,c){return '<div class="stat"><span>'+a+'</span><i>'+c+'</i><strong>'+b+'</strong></div>'}
function selectRoles(id,value){return '<select id="'+id+'"><option value="">اختار رتبة…</option>'+s.resources.roles.map(r=>'<option value="'+r.id+'" '+(String(value||"")===String(r.id)?"selected":"")+'>'+esc(r.name)+'</option>').join("")+'</select>'}
function selectChannels(id,value){return '<select id="'+id+'"><option value="">اختار قناة…</option>'+s.resources.channels.filter(c=>["text","news"].includes(c.type)).map(c=>'<option value="'+c.id+'" '+(String(value||"")===String(c.id)?"selected":"")+'># '+esc(c.name)+'</option>').join("")+'</select>'}
async function loadGuild(){try{[s.overview,s.resources]=await Promise.all([api("/api/guilds/"+s.guild.id+"/overview"),api("/api/guilds/"+s.guild.id+"/resources")]);clearWarn()}catch(e){warn("تعذر تحميل بيانات السيرفر: "+e.message)}$("#guildName").textContent=s.guild.name;$("#guildIcon").innerHTML=icon(s.guild)}
async function pick(id){s.guild=s.guilds.find(g=>String(g.id)===String(id));$("#guildSelect").value=s.guild.id;await loadGuild();render()}
const titles={overview:"Overview",servers:"السيرفرات",analytics:"Analytics",moderation:"Moderation",automod:"AutoMod",economy:"ANORIS Economy",tickets:"Tickets",levels:"Levels",giveaways:"Giveaways",welcome:"Welcome",commands:"Commands",shortcuts:"Shortcuts",resources:"القنوات والرتب",teams:"Teams",logs:"Logs",security:"Security",settings:"Settings"};
const desc={overview:"نظرة شاملة على حالة Ader والسيرفر.",analytics:"إحصائيات النشاط المسجلة فعلياً.",moderation:"الإشراف والتحذيرات والحماية التلقائية.",automod:"إعدادات AutoMod المبنية على نظام Ader.",economy:"إعدادات ANORIS وترتيب الأرصدة.",tickets:"لوحات التذاكر والتذاكر المفتوحة.",levels:"ترتيب XP والمستويات.",giveaways:"بيانات الهدايا المحفوظة.",welcome:"الترحيب والتحقق.",commands:"تحكم مباشر في أوامر Ader.",shortcuts:"إدارة الاختصارات النصية.",resources:"القنوات والرتب المتاحة.",teams:"الفرق الموثقة وإعداداتها.",logs:"سجل الأحداث والتحذيرات.",security:"حالة جلسة الدخول وصلاحياتك.",settings:"تفعيل وتعطيل أنظمة Ader."};
async function render(){const p=s.page;$("#title").textContent=titles[p]||p;document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));try{if(p==="overview")overview();else if(p==="servers")servers();else if(p==="resources")resources();else if(p==="analytics")await analytics();else if(p==="moderation"||p==="automod")await moderation();else if(p==="economy")await economy();else if(p==="levels")await levels();else if(p==="tickets")await tickets();else if(p==="welcome")await welcome();else if(p==="commands")await commands();else if(p==="shortcuts")await shortcuts();else if(p==="teams")await teams();else if(p==="logs")await logs();else if(p==="security")security();else if(p==="settings")await settings();else giveaways();}catch(e){if(e.message==="AUTH")showLogin();else warn("تعذر تحميل القسم: "+e.message)}bindCommon()}
function overview(){const o=s.overview||{};$("#root").innerHTML=head("مرحباً بك في Ader",desc.overview)+'<div class="stats">'+stat("الأعضاء",o.members||0,"♙")+stat("القنوات",o.channels||0,"#")+stat("الرتب",o.roles||0,"◆")+stat("التذاكر المفتوحة",o.open_tickets||0,"🎫")+'</div><div class="cards">'+card("System Health",'<div class="health"><div>Ader Bot <b>Online</b></div><div>Database <b>Connected</b></div><div>Commands <b>'+(o.commands||0)+'</b></div><div>Guilds <b>'+s.guilds.length+'</b></div></div>')+card("Quick Actions",'<div class="quick"><button class="action" data-go="moderation">🛡 Moderation</button><button class="action" data-go="economy">🪙 Economy</button><button class="action" data-go="tickets">🎫 Tickets</button><button class="action" data-go="settings">⚙ Settings</button></div>')+'</div>'}
function servers(){$("#root").innerHTML=head("السيرفرات","اختار السيرفر للإدارة.")+'<div class="server-grid">'+s.guilds.map(g=>'<button class="server" data-guild="'+g.id+'"><div class="avatar">'+icon(g)+'</div><b>'+esc(g.name)+'</b><small>'+(g.administrator?"Administrator":"Manage Server")+'</small></button>').join("")+'</div>'}
function resources(){const r=s.resources||{};$("#root").innerHTML=head("القنوات والرتب",desc.resources)+'<div class="cards">'+card("الرتب",'<div class="list">'+(r.roles||[]).map(x=>'<div><b>'+esc(x.name)+'</b><small>Position '+x.position+'</small></div>').join("")+'</div>')+card("القنوات",'<div class="list">'+(r.channels||[]).map(x=>'<div><b># '+esc(x.name)+'</b><small>'+esc(x.type)+'</small></div>').join("")+'</div>')+'</div>'}
async function analytics(){const d=await api("/api/guilds/"+s.guild.id+"/analytics?days=7"),c=d.counts||{};$("#root").innerHTML=head("Analytics",desc.analytics)+'<div class="stats">'+stat("الأحداث",d.total||0,"◔")+stat("Messages",c.message||0,"💬")+stat("Joins",c.member_join||0,"↗")+stat("Leaves",c.member_leave||0,"↘")+'</div>'+card("Daily Activity",'<div class="list">'+Object.entries(d.daily||{}).sort().map(([day,v])=>'<div><b>'+esc(day)+'</b><small>messages '+(v.message||0)+' · joins '+(v.member_join||0)+' · leaves '+(v.member_leave||0)+'</small></div>').join("")+'</div>')}
async function moderation(){const d=await api("/api/guilds/"+s.guild.id+"/moderation"),m=d.config||{},a=m.auto_mod||{};$("#root").innerHTML=head(titles[s.page],desc[s.page])+'<div class="cards">'+card("Module",'<label class="toggleline">Enabled <input type="checkbox" id="mod-enabled" '+(m.enabled!==false?"checked":"")+'></label>')+card("AutoMod",'<label>Spam Detection<input type="checkbox" id="spam" '+(a.spam_detection!==false?"checked":"")+'></label><label>Max Mentions<input id="mentions" type="number" min="0" max="50" value="'+(a.max_mentions??5)+'"></label><label>Toxicity Filter<input type="checkbox" id="tox" '+(a.toxicity_filter!==false?"checked":"")+'></label><button class="primary smallbtn" id="save-mod">حفظ</button>')+card("Warnings",'<div class="big-number">'+(d.warning_count||0)+'</div>'+(d.warnings||[]).slice(0,10).map(w=>'<div class="logline"><b>User '+w.user_id+'</b><small>'+esc(w.reason)+'</small></div>').join(""))+'</div>';$("#save-mod").onclick=async()=>{await api("/api/guilds/"+s.guild.id+"/modules/moderation",{method:"PUT",body:JSON.stringify({enabled:$("#mod-enabled").checked,auto_mod:{spam_detection:$("#spam").checked,max_mentions:Number($("#mentions").value),toxicity_filter:$("#tox").checked}})});await loadGuild();await moderation()}}
async function economy(){const d=await api("/api/guilds/"+s.guild.id+"/economy"),c=d.config||{};$("#root").innerHTML=head("ANORIS Economy",desc.economy)+'<div class="cards">'+card("Currency",'<label>الاسم<input id="cur-name" value="'+esc(c.currency_name||"ANORIS")+'"></label><label>الرمز<input id="cur-symbol" value="'+esc(c.currency_symbol||"🪙")+'"></label><label>Daily Reward<input id="daily" type="number" min="0" value="'+(c.daily_reward??30)+'"></label><button class="primary smallbtn" id="save-econ">حفظ</button>')+card("Leaderboard",'<div class="list">'+(d.leaderboard||[]).map((x,i)=>'<div><b>#'+(i+1)+' · User '+x.user_id+'</b><span>'+Number(x.balance||0).toLocaleString()+' '+esc(c.currency_name||"ANORIS")+'</span></div>').join("")+'</div>')+'</div>';$("#save-econ").onclick=async()=>{await api("/api/guilds/"+s.guild.id+"/modules/economy",{method:"PUT",body:JSON.stringify({currency_name:$("#cur-name").value,currency_symbol:$("#cur-symbol").value,daily_reward:Number($("#daily").value)})});await economy()}}
async function levels(){const d=await api("/api/guilds/"+s.guild.id+"/levels");$("#root").innerHTML=head("Levels",desc.levels)+card("XP Leaderboard",'<div class="list">'+(d.users||[]).map((x,i)=>'<div><b>#'+(i+1)+' · User '+x.user_id+'</b><small>Level '+x.level+' · '+Number(x.xp||0).toLocaleString()+' XP</small></div>').join("")+'</div>')}
async function tickets(){const d=await api("/api/guilds/"+s.guild.id+"/tickets");$("#root").innerHTML=head("Tickets",desc.tickets)+'<div class="cards">'+card("Panels",'<div class="list">'+(d.panels||[]).map(x=>'<div><b>'+esc(x.title||"Ticket Panel")+'</b><button class="action danger" data-delete-panel="'+x.id+'">حذف</button></div>').join("")+'</div>')+card("Tickets",'<div class="list">'+(d.tickets||[]).slice(0,30).map(x=>'<div><b>#'+x.id+' · '+esc(x.status)+'</b><small>channel '+esc(x.channel_id||"—")+' · user '+esc(x.user_id||"—")+'</small></div>').join("")+'</div>')+'</div>';document.querySelectorAll("[data-delete-panel]").forEach(b=>b.onclick=async()=>{if(confirm("تحذف اللوحة؟")){await api("/api/guilds/"+s.guild.id+"/tickets/panels/"+b.dataset.deletePanel,{method:"DELETE"});await tickets()}})}
async function welcome(){const d=await api("/api/guilds/"+s.guild.id+"/welcome"),g=d.config||{},m=d.module||{};$("#root").innerHTML=head("Welcome",desc.welcome)+'<div class="cards">'+card("Verification Module",'<label>Enabled<input type="checkbox" id="ver-enabled" '+(m.enabled!==false?"checked":"")+'></label><label>Method<select id="ver-method"><option value="dm" '+(g.verification_method==="dm"?"selected":"")+'>DM</option><option value="channel" '+(g.verification_method==="channel"?"selected":"")+'>Channel</option></select></label><label>Type<input id="ver-type" value="'+esc(g.verification_type||"button")+'"></label>')+card("Channels & Role",'<label>Verified Role'+selectRoles("ver-role",g.verified_role)+'</label><label>Welcome Channel'+selectChannels("welcome-channel",g.welcome_channel)+'</label><label>Verify Channel'+selectChannels("verify-channel",g.verify_channel)+'</label>')+card("Welcome Message",'<textarea id="welcome-message" rows="7">'+esc(g.welcome_message||"مرحبا {user} 👋")+'</textarea><button class="primary smallbtn" id="save-welcome">حفظ</button>')+'</div>';$("#save-welcome").onclick=async()=>{await api("/api/guilds/"+s.guild.id+"/settings",{method:"PUT",body:JSON.stringify({modules:{verification:{enabled:$("#ver-enabled").checked}},verification:{verified_role:$("#ver-role").value||null,welcome_channel:$("#welcome-channel").value||null,verify_channel:$("#verify-channel").value||null,verification_method:$("#ver-method").value,verification_type:$("#ver-type").value,welcome_message:$("#welcome-message").value}})});await welcome()}}
async function commands(){const d=await api("/api/guilds/"+s.guild.id+"/commands");$("#root").innerHTML=head("Commands",desc.commands)+card("الأوامر",'<div class="list">'+(d.commands||[]).map(c=>'<div><span><b>/'+esc(c.name)+'</b><small>'+esc(c.description||"بدون وصف")+'</small></span><label class="switch"><input type="checkbox" data-command="'+esc(c.name)+'" '+(c.enabled?"checked":"")+'><i></i></label></div>').join("")+'</div>');document.querySelectorAll("[data-command]").forEach(x=>x.onchange=async()=>{try{await api("/api/guilds/"+s.guild.id+"/commands/"+encodeURIComponent(x.dataset.command),{method:"PUT",body:JSON.stringify({enabled:x.checked})})}catch(e){x.checked=!x.checked;warn(e.message)}})}
async function shortcuts(){const d=await api("/api/guilds/"+s.guild.id+"/shortcuts");$("#root").innerHTML=head("Shortcuts",desc.shortcuts)+card("الاختصارات",'<div class="list">'+(d.shortcuts||[]).map(x=>'<div class="shortcut-row"><span><b>'+esc(x.label)+'</b><small>'+esc(x.name)+'</small></span><input data-alias="'+esc(x.name)+'" value="'+esc(x.alias||"")+'"><label class="switch"><input type="checkbox" data-shortcut="'+esc(x.name)+'" '+(x.enabled?"checked":"")+'><i></i></label><button class="action" data-save-shortcut="'+esc(x.name)+'">حفظ</button></div>').join("")+'</div>');document.querySelectorAll("[data-save-shortcut]").forEach(b=>b.onclick=async()=>{const n=b.dataset.saveShortcut;try{await api("/api/guilds/"+s.guild.id+"/shortcuts/"+encodeURIComponent(n),{method:"PUT",body:JSON.stringify({alias:document.querySelector("[data-alias='"+CSS.escape(n)+"']").value,enabled:document.querySelector("[data-shortcut='"+CSS.escape(n)+"']").checked})});b.textContent="تم"}catch(e){warn(e.message)}})}
async function teams(){const [d,ts]=await Promise.all([api("/api/guilds/"+s.guild.id+"/teams"),api("/api/guilds/"+s.guild.id+"/teams/settings")]);const cfg=ts.settings||{};$("#root").innerHTML=head("Teams",desc.teams)+'<div class="cards">'+card("Team Settings",'<label>Coach Role'+selectRoles("coach-role",cfg.coach_role_id)+'</label><label>Max Players<input id="max-players" type="number" min="1" max="200" value="'+(cfg.max_players||15)+'"></label><button class="primary smallbtn" id="save-team">حفظ</button>')+card("Verified Teams",'<div class="list">'+(d.teams||[]).map(x=>'<div><b>'+esc(x.emoji||"👥")+' '+esc(x.name)+'</b><small>'+esc(x.team_type)+' · '+x.players+' players · role '+x.role_id+'</small></div>').join("")+'</div>')+'</div>';$("#save-team").onclick=async()=>{await api("/api/guilds/"+s.guild.id+"/teams/settings",{method:"PUT",body:JSON.stringify({coach_role_id:$("#coach-role").value||null,max_players:Number($("#max-players").value)})});await teams()}}
async function logs(){const d=await api("/api/guilds/"+s.guild.id+"/logs");$("#root").innerHTML=head("Logs",desc.logs)+card("Recent Activity",'<div class="list">'+(d.logs||[]).map(x=>'<div><b>'+esc(x.type)+'</b><small>'+esc(new Date(Number(x.timestamp)*1000).toLocaleString())+' · '+esc(JSON.stringify(x.data||{}))+'</small></div>').join("")+'</div>')}
function security(){$("#root").innerHTML=head("Security",desc.security)+'<div class="cards">'+card("Session",'<div class="kv"><span>User</span><b>'+esc(s.user?.username||"Discord User")+'</b></div><div class="kv"><span>Managed Servers</span><b>'+s.guilds.length+'</b></div>')+card("OAuth",'<div class="empty small">State validation مفعّل، session cookie Secure + SameSite=Lax، وAPI الإداري كيتحقق من صلاحية السيرفر.</div>')+'</div>'}
async function settings(){const d=await api("/api/guilds/"+s.guild.id+"/settings"),m=d.modules||{},names=["moderation","verification","analytics","economy","leveling","roles","tickets","games"];$("#root").innerHTML=head("Settings",desc.settings)+card("Modules",'<div class="list">'+names.map(n=>'<div><b>'+n+'</b><label class="switch"><input type="checkbox" data-module="'+n+'" '+(m[n]?.enabled!==false?"checked":"")+'><i></i></label></div>').join("")+'</div>');document.querySelectorAll("[data-module]").forEach(x=>x.onchange=async()=>{try{await api("/api/guilds/"+s.guild.id+"/modules/"+x.dataset.module,{method:"PUT",body:JSON.stringify({enabled:x.checked})})}catch(e){x.checked=!x.checked;warn(e.message)}})}
function giveaways(){const rows=s.overview||{};$("#root").innerHTML=head("Giveaways",desc.giveaways)+card("Status",'<div class="empty small">قاعدة البيانات فيها جدول giveaways، ولكن main.py حالياً ما كيحملش cog مستقل ديال giveaways؛ لذلك هاد القسم ما غاديش يوهمك بوجود إنشاء غير مربوط.</div>')}
function bindCommon(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>{s.page=b.dataset.go;render()});document.querySelectorAll("[data-guild]").forEach(b=>b.onclick=()=>pick(b.dataset.guild))}
async function boot(){try{const me=await api("/api/me");if(!me.logged_in)return showLogin();s.user=me.user;const g=await api("/api/guilds");s.guilds=g.guilds||[];showApp();if(!s.guilds.length){$("#root").innerHTML='<div class="empty">ما كاين حتى سيرفر متاح للإدارة.</div>';return}s.guild=s.guilds[0];$("#user").textContent=(s.user.username||"U")[0];$("#guildSelect").innerHTML=s.guilds.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join("");$("#guildSelect").onchange=()=>pick($("#guildSelect").value);await loadGuild();await render()}catch(e){if(e.message==="AUTH")showLogin();else{showLogin();warn("تعذر الاتصال بالـAPI: "+e.message)}}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{s.page=b.dataset.page;render()});$("#loginBtn").onclick=()=>location.href=API+"/login";$("#logoutBtn").onclick=()=>location.href=API+"/logout";$("#refresh").onclick=()=>loadGuild().then(render);$("#theme").onclick=()=>document.body.classList.toggle("light");$("#menu").onclick=()=>$("#sidebar").classList.toggle("open");boot();
})();